id: A81DE519D
title: 'The Magical Lasso: A Prayer of Aspiration to Accomplish Khecara'
type: translation
pechas:
- IF6111008
- IBADB8DFA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:56:53.430707
  last_modified_at: 2023-01-04 12:56:53.430727
  collections:
  - Lelung Shepé Dorje Series
  - Works of Tibetan Masters
alignment_to_base:
  IF6111008/8F97: 043E
  IBADB8DFA/9B4C: 043E
